### ISSUE TITLE
When open a non-utf8 text file, the txt will be garbled.

### ISSUE THREAD

**Issue by sdutwsl** [GoogleChromeLabs/text-editor#27]
As most Windows text files is not encoded as utf8, is there any solution to solve this problem?

**Comment by ghost** [comment]
I'm not sure if there is a way to make this happen, TextDecoder and TextEncoder only support UTF-8, and ECMAScript strings are always in UTF-16. Maybe the native file API or Blob API has something I've missed.

If I might ask, what encoding are your files in?

Would it be easy to change your settings or something in order to use UTF-8 when storing files, are there any particular reasons that they are in the encoding that they are currently in?

**Comment by sdutwsl** [comment]
For most Windows OS, for historical reason, they don't use utf-8 as the default encoding.In my region, it's most GBK/GBK2312 or unicode(windows native notepad can see this encoding, not same as utf-8).

To change Windows10 to use utf-8, it can be done with settings in
Control Panel -> Region -> Manage -> Change system region setting

To change a text file, it can be done with native notepad's 'Save as (Control + Shift + S )' option in the menu's 'File' option. 

I wonder if this problem can be solved by native JS/ES method, or it may become a limit for Native-Like web app development using JS file APIs.

**Comment by ghost** [comment]
And just to confirm, this affects both, saving and downloading, correct?

If LePage doesn't check up on this anytime soon, I'll look around, since I had forked, heavily modified, looked over the code already.

But then again, this is only a demo of an experimental, non-standard API.

**Comment by sdutwsl** [comment]
Well, it's a little complex on those conditions.

For test, I support a text file at
[https://github.com/sdutwsl/Testtxt/blob/main/not-utf8-test.txt](https://github.com/sdutwsl/Testtxt/blob/main/not-utf8-test.txt)
which is encoded with GBK2312.

You can download and open/save/save as it with online text editor or notepad for tests.

I'm suprised for github can display it correnctly.I guess for .txt files, github dealed their content on the server side with encoding judging and then translated the contents to utf-8.

**Comment by ghost** [comment]
> For test, I support a text file at
> https://github.com/sdutwsl/Testtxt/blob/main/not-utf8-test.txt
> which is encoded with GBK2312.

Oh, that is interesting, GitHub can indeed show it in UTF-8, and I agree, it is likely server-side encoding changes.

Yet the only possible solution that I, as an individual, could come up with would be accepting files on a per-encoding basis and decoding each with a preset encoder/decoder.

As it would turn out, contrary to what I had said back at
> ...TextDecoder and TextEncoder only support UTF-8...

according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/TextDecoder), they do indeed support other encodings, including the one that your desktop is using.
I set up a quick test using that file you linked and it works perfectly: https://decode.xxperthacker.repl.co/index.xhtml

The only problem is determining what encoding the file is that the user has uploaded, as it doesn't seem like the File/Blob APIs or the new native file API being demoed exposes this much information.

So, we *can* convert between encodings, but without a way to determine what encoding is in use, we can't determine which decoding algorithm to use.

Maybe I'm missing something, or someone else knows a way?

**Comment by sdutwsl** [comment]
> The only problem is determining what encoding the file is that the user has uploaded, as it doesn't seem like the File/Blob APIs or the new native file API being demoed exposes this much information.
> 
> So, we _can_ convert between encodings, but without a way to determine what encoding is in use, we can't determine which decoding algorithm to use.
> 

For  language/encoding detection, it indeed shoudn't be supplied by programming language itself or it's native APIs, but a third-party library.

For algorithm, we can refer to this article:
[https://www-archive.mozilla.org/projects/intl/universalcharsetdetection](https://www-archive.mozilla.org/projects/intl/universalcharsetdetection)

There is an an existing language/encoding detection lib for Python name chardet:
[https://github.com/chardet/chardet](https://github.com/chardet/chardet)

As an addition, some unicode text file have a BOM(Byte Order Mark) field at it's start, but not for all.

**Comment by ghost** [comment]
It would sure be nice if those could be ported to the web app (ideally as Wasm), and ran against the page to make it transparent, but that would take quite some time. In the meanwhile, I'll try to fork this, and simply set up a new menu that allows the user to choose their preferred encoding (defaulting to UTF-8?) and add a new property in the `app` object to store the current encoding.

That should push it towards being more like the native NotePad.

Thinking about it, I'll likely have to set up saving the user choice too, but that could come slightly later.

The only real problem would be getting the pull request merged.

**Comment by ghost** [comment]
Found a [useful part of the spec](https://encoding.spec.whatwg.org/), forked this project, started implementation, and made major progress.

You can check it out until it's done, but once it is, I'll create a PR here and try to merge it here: https://github.com/00ff0000red/text-editor.

Should be done within the week at longest.

The next step is to figure out how to make that link I gave earlier (https://decode.xxperthacker.repl.co/main.mjs) work on text instead. I had used [Blob.prototype.arrayBuffer](https://developer.mozilla.org/en-US/docs/Web/API/Blob/arrayBuffer) with success, but trying to use plain text data fails poorly.

**Comment by sdutwsl** [comment]
Good work, I'll watch it.

> The next step is to figure out how to make that link I gave earlier (https://decode.xxperthacker.repl.co/main.mjs) work on text instead. I had used [Blob.prototype.arrayBuffer](https://developer.mozilla.org/en-US/docs/Web/API/Blob/arrayBuffer) with success, but trying to use plain text data fails poorly.

I don't quite understand 'plain text data' mean. In my opinion, the bahavior of TextDecoders only working with raw data(binary data) is properly because the data of decoder to deal with is raw data.

And also the other language do it as above, for example like java:
```
String s="你好";
try{
	byte[] bytes=s.getBytes("gbk");
	for (byte b : bytes) {
		System.out.println(Integer.toBinaryString(b));
	}
}catch(Exception e)
{
}

/****   the output
11111111111111111111111111000100
11111111111111111111111111100011
11111111111111111111111110111010
11111111111111111111111111000011
****/
```
We can see, the return value of getBytes is byte[], the binary data.

**Comment by ghost** [comment]
> I don't quite understand 'plain text data' mean. In my opinion, the bahavior of TextDecoders only working with raw data(binary data) is properly because the data of decoder to deal with is raw data.

Sorry, I was vague there.

I meant JavaScript's `string` type, as opposed to an `ArrayBuffer`.

I had done
```js
new TextDecoder(...).decode(arrayBuffer);

new TextDecoder(...).decode( new TextEncoder().encode(string) );
```
For some reason, the latter failed, while the ArrayBuffer worked, so I have some debugging to do.

JavaScript's `TextEncoder` should be equivalent to Java's `String.getBytes`, it just converts the string into bytes.

Oh, that Java is giving 32-bit integers, not bytes?

**Comment by sdutwsl** [comment]
I see.

But why TextDecoder failed to decode the Uint8Array data that TextEncoder returned, I don't know too.I tried it and the result was the same.

I think it's right for
>JavaScript's ```TextEncoder``` should be equivalent to Java's ```String.getBytes```

But it return 8-bit bytes array.The print output was 32-bit integers is because I call ```Integer.toBinaryString(b)``` to change it to 32-bit binary form.

**Comment by ghost** [comment]
@sdutwsl I finally got around to it today. I learned a bit about ECMAScript strings, a bit about ArrayBuffers, and set up a crappy implementation.
I think you'll be pleased to see it.
Example implementation hosted on Repl: <https://encoding-pr.xxperthacker.repl.co>.

The encodings list really needs to be fixed, I'm thinking something more like the simple HTML `<select />` tag.

If you type without saving and choose a new encoding, it will fail horribly, don't try it. I'll fix it later.

If you choose an encoding, it is saved until the next time you load the app.

If you open a file with an encoding chosen, the file is read and loaded using that encoding.

After I determine a good way to handle the unsaved file with new encoding, this should be able to be integrated into the primary app.

**Comment by ghost** [comment]
Any suggestions?
Do you support what's being done here @petele?

**Comment by sdutwsl** [comment]
Haha, beautiful work. Thanks for your patience, and I think what you did will be useful in future.

**Comment by ghost** [comment]
@sdutwsl Have you tried it out yet? If so, can you inform me of whether or not the files are being written in the chosen encoding?

I think it messes up any files when writing to them, and I wouldn't want to destroy the user's file system when using the app.

**Comment by sdutwsl** [comment]
I'd simply tried it to read a GBK file last time, it works properly.

And just now I tried writing a text file.

But when writing a file, the encoding is UTF-8 whichever encoding I choosed in my case.

**Comment by ghost** [comment]
> But when writing a file, the encoding is UTF-8 whichever encoding I chose in my case.

Yes, it's as I had expected, I never set it up to properly write to the file using the encoding, so it's essentially just as useless as before.

Don't try the encodings until I've got the saving done right (unless you want to just use UTF-8) because otherwise, it will just maul your files.

I'll report back soon with an update, and a whole PR, hopefully by the end of the week.

**Comment by ghost** [comment]
I have to back off of this, turns out I didn't have the time.
We need the actual author to handle this instead.

**Comment by sdutwsl** [comment]
Haha, I think it's no problem.
The charset or encoding of texts is really historical problem and time will solve it.
For example most of operating system change their encodings into UTF-8, even Windows could change its default encoding to UTF-8.
But what you contributed is also important for improving user experience of this project, and inspiring for others who wants to deal with the same problem.
